### ISSUE TITLE
crashing and bringing up esc menu

### ISSUE THREAD

**Issue by JBennito** [jsbots/AutoFish#25]
I'm not sure if I have something configured incorrectly, but it will work successfully for between 1 to 8 (max so far) casts and catches, then it will bring up the in-game ESC menu and AutoFish will crash/freeze up. Has anyone else experienced this? 

I'm in wotlk classic running 1920x1080 windowed mode, DirectX11, logging out option unselected, random sleep unselected, and with whitelist/loot all uncommon and rare.

**Comment by olesgeras** [comment]
Did you turn off AutoLoot? The problem also might be related to latency issues with Dragonflight release, because loot window is opened too late. Working right now to deal with the issue, so wait for updates.

**Comment by JBennito** [comment]
I did turn off AutoLoot and that seemed to fix that issue, so thank you. Now though it doesn't seem like the whitelist will loot anything. I made the name in-game is exactly the same as what I've input. Perhaps this is a latency issue? I run about 173ms.

**Comment by olesgeras** [comment]
What resolution you are playin on?

**Comment by JBennito** [comment]
I've tried both fullscreen and windowed 1920x1080, render scale at 100% and 200%. I've also tried windowed 1600x900 with 100% render scale. None of them seemed to loot anything without autoloot on (though of course autoloot on crashes after 1-8 catches).

**Comment by olesgeras** [comment]
Did you turn off scaling?

**Comment by JBennito** [comment]
Render scale set at 100, all addons are disabled, and UI scale is turned off.

![image](https://user-images.githubusercontent.com/116713834/197992866-69a88677-74d4-45f6-b038-5b0585fca945.png)
![image](https://user-images.githubusercontent.com/116713834/197993015-c4a44808-38a8-4279-ab33-1c2f57113879.png)

**Comment by olesgeras** [comment]
make a screenshot of the UI of the bot

**Comment by JBennito** [comment]
![image](https://user-images.githubusercontent.com/116713834/197999665-1cb0e787-b781-4336-b636-80ee7e64b015.png)
![image](https://user-images.githubusercontent.com/116713834/197999758-f0d9f1f6-8422-489e-a512-ec36e63dfe66.png)
![image](https://user-images.githubusercontent.com/116713834/197999829-ccdd7790-01cd-4e85-874b-3196a76b1026.png)

**Comment by olesgeras** [comment]
Record the whole fishing process and find me in discord
