### ISSUE TITLE
Can't automatically download chi_sim language data of tesseract.js

### ISSUE THREAD

**Issue by 5oulReaper** [jsbots/AutoFish#28]
Thanks for the brilliant work. The bot works well in the English version, but I had to switch the Game from Chinese to English every time I used the bot.
I tried to set the whitelist to "chi_sim", but it seems the bot can't automatically download the chi_sim language data of tesseract.js.
Are there any other means I could download the chi_sim language data? Thanks again from a Chinses user.

**Comment by jsbots** [comment]
You can download traindata file manually from [tesseract languages](https://tesseract-ocr.github.io/tessdoc/Data-Files#data-files-for-version-400-november-29-2016) and drop it into the root folder of the bot.
