### ISSUE TITLE
Interaction Key not working properly

### ISSUE THREAD

**Issue by totalschaden** [jsbots/AutoFish#36]
Sometime the Interaction Key is not pressed/detected by the wow client.

Maybe the "pressed" time is to short for slow system ?

Any chance we get a Interaction Key Pressed for x ms setting ?

I think this would help with the problem.

**Comment by jsbots** [comment]
Have you applied these commands?

```
/console SoftTargetInteractArc 2
/console SoftTargetInteractRange 30
```

> Any chance we get a Interaction Key Pressed for x ms setting ?

There's such an option in the Advanced Settings, it's called "**Mouse/keyboard random delay**"

**Comment by totalschaden** [comment]
Managed to fix it, vm had bad performence. i was talking about the keyDown/keyup time, or is "Mouse/keyboard random delay" that ? was thinking this is related to reaction speed

**Comment by jsbots** [comment]
**Mouse/keyboard random delay** is a delay value between "_keyDown/keyUp_", there's a different option for reaction in the Advanced Settings.
