### ISSUE TITLE
no longer works in windowed maximized mode

### ISSUE THREAD

**Issue by orcutt989** [jsbots/AutoFish#44]
I've been using AutoFish for over a month without problem, but I can't seem to get it to detect the bobber any more.  Could have also been the latest Turtle WOW update as well perhaps? I did notice that it the cursor WILL move AFTER I stop the bot sometimes to where the bobber is.

EDIT: Doesnt seem to work in Windowed >> Maximized mode anymore. If i untick "maximized" it seems to work OK.

**Comment by jsbots** [comment]
Just tested it. Works properly with both modes for me. Does an old version works properly if you test it now? Have you tried to launch the bot as admin?

**Comment by orcutt989** [comment]
Might have something to do with vanilla fixes? Does that help at all?
