### ISSUE TITLE
Not applying lure freqvent in wow classic

### ISSUE THREAD

**Issue by Navic9** [jsbots/AutoFish#52]
Hi,

Program works good except the lures.

When I start the program it apply lure (10min) and start fishing.

When lure expire sometimes it apply now but sometimes it dont, and then you start fishing with to low skill and catch nothing.

I have played around with the settings but nothing seems to help to have 100% uptime with the lure.

The lure duration is 10min, and it is 5500ms to apply, just like setting say.

Anyone have any suggestion what this can be? I have done the macro needed etc but its like the bot just is not pressing the key every 10 min like it should.

**Comment by onurycl** [comment]
i got same issue lure is not reapplying or reappliying randomly random time after finished

**Comment by jsbots** [comment]
https://github.com/jsbots/AutoFish/releases/tag/v2.2.4

**Comment by onurycl** [comment]
ok this time i got another issue 
which is
bot is not respond to loot window whitelist or blacklist doesnt matter it does not loot

**Comment by onurycl** [comment]
non human mouse movement

**Comment by jsbots** [comment]
> non human mouse movement

Does it work with "like a human" option? What game are we talking about?

**Comment by onurycl** [comment]
i am not using like a human option
and using in era

**Comment by jsbots** [comment]
> i am not using like a human option
I understood that, I'm asking whether you have an issue IF you use it (test it if you haven't yet), to understand whether it's related to "like a human" option.
