### ISSUE TITLE
Not casting in Ascension Wow

### ISSUE THREAD

**Issue by davenate90** [jsbots/AutoFish#56]
I'm not sure what is causing the issue here but the symptoms are:
1. The program doesn't cast fishing. I set the key to 1 and the fishing ability to key 1.
2. The program doesn't catch the fish in time. It says found the bobber, and reads checking hook but always results in fish got away. 

potential issues: 
1. Ascension wow has a custom window called Ascension.
2. Not sure if it's running in DirectX 11 or not. I have no option to change that.

**Comment by himaelkady** [comment]
Did you find the solution for it?

**Comment by jsbots** [comment]
> Did you find the solution for it?

Try to run the bot as admin.

**Comment by himaelkady** [comment]
> > Did you find the solution for it?
> 
> Try to run the bot as admin.

Thank you!
