### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by journeym** [jsbots/AutoFish#61]
Is there some kind of build instructions for this?
How can i build the project under windows?

**Comment by journeym** [comment]
ok im able to run the app with npm start, but unable to build, with npm run build, the random.js is missing.
i presume this is some obfuscator to not get detected by server software you run each build?

**Comment by jsbots** [comment]
remove premake property from package.json

**Comment by journeym** [comment]
yeah i figured that out, thanks

**Comment by journeym** [comment]
So if anyone wondering, instructions for the process are:

- install node.js latest version
- install python **SPECIFIC** version 3.11.6 (currently latest has some dependency problems)
- run npm install
- remove "premake": "node random.js", from package.json
- run npm run make
