### ISSUE TITLE
Finds bobber but does not react on catch

### ISSUE THREAD

**Issue by baelrayneVessdren** [jsbots/AutoFish#71]
Hi.

Bobber is found but after bite there is no reaction. Does that after the bobber lands "further away". The closer it is to the player location / the bottom of the fishing zone, the more reliable it is working.

**Comment by jsbots** [comment]
Try to fish from the 1st person view or turn off auto sensitivity and tweak it manually.

**Comment by baelrayneVessdren** [comment]
Already fishing from 1st. Manual values only make it marginally better. 9 = hooks to early. 8 = catches 5-6 in row and starts not reacting again for several catches.

**Comment by jsbots** [comment]
What game is it? Can you record a video? Dm it to me in discord: https://discord.gg/4sHFUtZ8tC

**Comment by baelrayneVessdren** [comment]
Game: Cataclysm Classic (latest patch)
Will see about the video and send it to you.

**Comment by jsbots** [comment]
The issue was **elvui**. Make sure to turn off all the UI addons before using the bot.
