### ISSUE TITLE
The bot doesn't manage game windows properly in win7 

### ISSUE THREAD

**Issue by jsbots** [jsbots/AutoFish#9]
The bot captures the whole screen instead of the game windows and can't set a window foreground if it sets it from anything but the game window itself. 

To get around this, open the window of the game in the background and switch to the bot UI, so that you can see the game in the background. After that, move the bot window outside fishing zone and press start (otherwise it will capture the UI of the bot too and surely find some red colors there).

**Comment by jsbots** [comment]
Since 1.13.0 the bot doesn't work with Windows 7 anymore. The issue is closed until Windows 7 support is added again.

**Comment by BigKananga** [comment]
Where can I get v1.12.1? Only source code is available. Oldest installer is 1.13.6.

**Comment by jsbots** [comment]
> Where can I get v1.12.1? Only source code is available. Oldest installer is 1.13.6.

[AutoFish 1.12.1](https://drive.google.com/file/d/18wFtAZt3X59pAjyQrWR8yRQZR4dFbMUg/view?usp=sharing)

**Comment by BigKananga** [comment]
Thanks a lot!
